# Deploys ony the web app to the hosting server. This is used in the "Deploy Web App" workflow, which is triggered by a push to the main branch.
name: Deploy Web App
on:
  push:
    branches:
      - main
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Update submodules if any
      - name: Update submodules
        run: git submodule update --init --recursive -depth=1

      - name: Install dependencies
        run: npm install

      - name: Build the web app
        run: npm run compile-for-deployment

  setup-pages:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with: 
          path: WebApp

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: setup-pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4